name: goodman_photometry
channels:
  - defaults
dependencies:
  - pip
  - pip:
      - asciitree==0.3.3
      - astroplan==0.10.1
      - astropy==6.1.2
      - astropy-healpix==1.0.3
      - astropy-iers-data==0.2024.8.5.0.32.23
      - astroquery==0.4.7
      - astroscrappy==1.2.0
      - beautifulsoup4==4.12.3
      - build==1.2.2.post1
      - ccdproc==2.4.2
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==3.0.11
      - dask==2024.9.1
      - fasteners==0.19
      - fits-utilities==0.1.2
      - flake8==7.1.1
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - goodman-photometry==0.1.dev25+ge7351c1.d20241009
      - goodman-pipeline==1.3.8
      - html5lib==1.1
      - idna==3.7
      - imageio==2.35.1
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.2
      - keyring==25.3.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - locket==1.0.0
      - matplotlib==3.9.0
      - mccabe==0.7.0
      - more-itertools==10.3.0
      - networkx==3.3
      - numcodecs==0.13.1
      - numpy==2.0.1
      - packaging==24.1
      - pandas==2.2.2
      - partd==1.4.2
      - patsy==0.5.6
      - pillow==10.4.0
      - pycodestyle==2.12.1
      - pyerfa==2.0.1.4
      - pyflakes==3.2.0
      - pyparsing==3.1.2
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyvo==1.5.2
      - pyyaml==6.0.1
      - reproject==0.14.0
      - requests==2.32.3
      - scikit-image==0.24.0
      - scipy==1.14.0
      - six==1.16.0
      - soupsieve==2.5
      - statsmodels==0.14.2
